version: "3"

services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: none
  server:
    build: .
    command: nodemon index.js
    ports:
      - 3000
    environment:
      VIRTUAL_HOST: localhost
    volumes:
      - ./index.js:/app/index.js
